name: AGE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: frdmn/age-calculator-action@v1.1
        id: birthday
        with:
          date: '2003-06-19'
