name: "Age Calculator"

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  check-age:
    runs-on: ubuntu-latest
    steps:
      - uses: frdmn/age-calculator-action@v1.1
        id: birthday
        with:
          date: '2003-06-19'
