name: Update Age in README

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update-age:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update age
        run: |
          sed -i "s/print::age/20/" ./README.md
          cat ./README.md
