name: update README

env:
    JULIA_NUM_THREADS: 2

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
    workflow_dispatch:
    schedule:
        - cron: "0 0 18-20 6 *"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: julia-actions/setup-julia@latest
            - run: |
                  julia main.jl

                  git config --global user.name 'gael-lopes-da-silva'
                  git config --global user.email 'gael.lopes-da-silva@outlook.fr'

                  if ! git diff --quiet "README.md"; then
                      git add "README.md"
                      git commit -am "automated build"
                      git push
                  fi
