name: update README

env:
    JULIA_NUM_THREADS: 2

on:
    push:
        branches: ["main"]
    workflow_dispatch:
    schedule:
        - cron: "0 0 18-20 6 *"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Github checkout
              uses: actions/checkout@v2

            - name: Install julia
              uses: julia-actions/setup-julia@latest

            - name: Generate README.md
              run: julia main.jl

            - name: Commit
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                commit_message: Automated commit
                branch: main