name: update README

env:
    PYTHONUNBUFFERED: 1

on:
    push:
        branches: ["main"]
    workflow_dispatch:
    schedule:
        - cron: "0 0 18-20 6 *"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Github checkout
              uses: actions/checkout@v2

            - name: Install Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.x'

            - name: Generate README.md
              run: python main.py

            - name: Commit
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                commit_message: Automated commit
                branch: main
